### ISSUE TITLE
Invalid time value

### ISSUE THREAD

**Issue by takenalias** [reelyactive/pareto-anywhere#3] opened 2021-12-02 01:48 UTC
Hi I just installed Pareto, set up my Aruba APs to send data to it and I get the following error.

/home/ghs/reelyActive/pareto-anywhere/node_modules/barnacles-elasticsearch/lib/barnacleselasticsearch.js:108
  esRaddec.timestamp = new Date(esRaddec.timestamp).toISOString();
                                                    ^

RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at handleRaddec (/home/ghs/reelyActive/pareto-anywhere/node_modules/barnacles-elasticsearch/lib/barnacleselasticsearch.js:108:53)

![image](https://user-images.githubusercontent.com/11468979/144342603-98733ac9-04c1-4b6c-a027-b9670ecd3a4e.png)

**Comment by jeffyactive** [comment] 2021-12-08 15:16
Glad you were able to set up your Aruba APs to forward data to Pareto Anywhere @takenalias 

The issue you raise is indeed a known bug that happens occasionally and is difficult to reproduce (and debug).

The current workaround is either to:
- run Pareto Anywhere as a service, so that it restarts automatically
- trim Pareto Anywhere down to just the modules essential for your application (if you remove barnacles-elasticsearch, the bug should no longer occur)

You can keep this issue open and we'll close when there is a full resolution.  Thanks!

**Comment by jeffyactive** [comment] 2022-03-03 13:51
This issue was addressed in barnacles-elasticsearch@1.0.2 which is included in pareto-anywhere@1.6.0, and appears to be resolved.  In other words, Pareto Anywhere should no longer experience occasional crashes due to a missing timestamp property.

Marking the issue as closed, thanks @takenalias for your contribution.

**Closed by jeffyactive** 2022-03-03 13:51 UTC
